"""Confirmed material production, validation, and catalog boundary."""

from .adapters import (
    AdapterRegistry,
    DeterministicLocalMediaAdapter,
    DeterministicLocalVideoAdapter,
    ManualImportAdapter,
    MaterialProductionAdapter,
    PRODUCTION_CAPABILITY_KINDS,
    PROVIDER_ADAPTER_PARAMETER,
    UnconfiguredProviderAdapter,
    UserMaterialRequestAdapter,
    build_creation_capability_reference,
    build_material_production_registry,
)
from .hyperframes import (
    HYPERFRAMES_PROVIDER_VERSION,
    HYPERFRAMES_WORKFLOW_PARAMETER,
    HyperFramesCLIRunner,
    HyperFramesMaterialProductionAdapter,
    HyperFramesProviderConfig,
    HyperFramesRunner,
    HyperFramesWorkflowSpec,
    load_hyperframes_provider_config,
    provider_config_path as hyperframes_provider_config_path,
)
from .agent import (
    MATERIAL_PRODUCTION_AGENT_VERSION,
    MaterialProductionAgent,
    MaterialProductionAgentError,
    MaterialProductionAgentReport,
    MaterialProductionAgentRequest,
)
from .comfyui import (
    COMFYUI_PROVIDER_VERSION,
    COMFYUI_WORKFLOW_PARAMETER,
    ComfyUIHTTPTransport,
    ComfyUIMaterialProductionAdapter,
    ComfyUIProviderConfig,
    ComfyUITransport,
    ComfyUIWorkflowBinding,
    ComfyUIWorkflowSpec,
    load_comfyui_provider_config,
    provider_config_path,
)
from .models import (
    MATERIAL_PRODUCTION_VERSION,
    AdapterCapability,
    AdapterJobUpdate,
    AdapterRegistryReference,
    ArtifactCandidate,
    ArtifactDecision,
    ArtifactValidation,
    MaterialCatalogDocument,
    MaterialCatalogEntry,
    MaterialAnalysisSummary,
    MaterialDerivative,
    MaterialQualityCheck,
    MaterialQualityReport,
    MaterialTag,
    MaterialProductionEvent,
    MaterialProductionLedger,
    MaterialProductionRunRequest,
    MaterialProductionView,
    ProductionJobRequest,
    ProductionPlanConfirmationReference,
    ProductionTaskInput,
)
from .ingest import MaterialIngestBundle, MaterialIngestError, MaterialIngestPipeline
from .service import MaterialProductionError, MaterialProductionOrchestrator
from .store import (
    MaterialCatalogStore,
    MaterialProductionConcurrencyError,
    MaterialProductionIntegrityError,
    MaterialProductionStore,
    MaterialProductionStoreError,
)
from .validation import ArtifactValidator

__all__ = [
    "MATERIAL_PRODUCTION_VERSION",
    "AdapterCapability",
    "AdapterJobUpdate",
    "AdapterRegistry",
    "AdapterRegistryReference",
    "ArtifactCandidate",
    "ArtifactDecision",
    "ArtifactValidation",
    "ArtifactValidator",
    "COMFYUI_PROVIDER_VERSION",
    "COMFYUI_WORKFLOW_PARAMETER",
    "ComfyUIHTTPTransport",
    "ComfyUIMaterialProductionAdapter",
    "ComfyUIProviderConfig",
    "ComfyUITransport",
    "ComfyUIWorkflowBinding",
    "ComfyUIWorkflowSpec",
    "HYPERFRAMES_PROVIDER_VERSION",
    "HYPERFRAMES_WORKFLOW_PARAMETER",
    "HyperFramesCLIRunner",
    "HyperFramesMaterialProductionAdapter",
    "HyperFramesProviderConfig",
    "HyperFramesRunner",
    "HyperFramesWorkflowSpec",
    "DeterministicLocalMediaAdapter",
    "DeterministicLocalVideoAdapter",
    "MATERIAL_PRODUCTION_AGENT_VERSION",
    "ManualImportAdapter",
    "MaterialCatalogDocument",
    "MaterialCatalogEntry",
    "MaterialAnalysisSummary",
    "MaterialDerivative",
    "MaterialIngestBundle",
    "MaterialIngestError",
    "MaterialIngestPipeline",
    "MaterialQualityCheck",
    "MaterialQualityReport",
    "MaterialTag",
    "MaterialCatalogStore",
    "MaterialProductionAdapter",
    "MaterialProductionAgent",
    "MaterialProductionAgentError",
    "MaterialProductionAgentReport",
    "MaterialProductionAgentRequest",
    "MaterialProductionConcurrencyError",
    "MaterialProductionError",
    "MaterialProductionEvent",
    "MaterialProductionIntegrityError",
    "MaterialProductionLedger",
    "MaterialProductionOrchestrator",
    "MaterialProductionRunRequest",
    "MaterialProductionStore",
    "MaterialProductionStoreError",
    "MaterialProductionView",
    "PRODUCTION_CAPABILITY_KINDS",
    "PROVIDER_ADAPTER_PARAMETER",
    "ProductionJobRequest",
    "ProductionPlanConfirmationReference",
    "ProductionTaskInput",
    "UnconfiguredProviderAdapter",
    "UserMaterialRequestAdapter",
    "build_creation_capability_reference",
    "build_material_production_registry",
    "load_comfyui_provider_config",
    "load_hyperframes_provider_config",
    "hyperframes_provider_config_path",
    "provider_config_path",
]
